spring:
  application:
    name: nacos-consumer
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 146.56.197.176:8848
        namespace: d4d9df21-38b3-4077-ab84-277dbb5eb13e
        group: codefusionary
server:
  port: 8080

# 日志配置
logging:
  level:
    root: INFO
    com.codefusionary: DEBUG

# Feign 配置
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  compression:
    request:
      enabled: true
    response:
      enabled: true

# Actuator 配置
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
